name: Tests
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: 14
          postgresql db: deploy_engine_test
          postgresql user: test
          postgresql password: password
      - name: Run tests
        run: |
          bin/rails db:setup
          bin/rspec
        env:
          DATABASE_URL: postgres://test:password@127.0.0.1:5432/deploy_engine_test
          RACK_ENV: test
      - name: Updload code coverage results
        uses: codecov/codecov-action@v3